### ISSUE TITLE
how can some files be smaller than the baseline?

### ISSUE THREAD

**Issue by hugoledoux** [FHOOEAIST/geofiles#29]
Just a question: I noticed that some files are smaller than the baseline OBJ (mostly CityJSON, geoobj, geoply) and I am puzzled. Is it because you took the OBJ file as is and it contains vertex normals and face normals?

**Comment by cpraschl** [comment]
No, the OBJ files are feature normalized for the comparison and like this, normals are removed.

There are different reasons for the size difference compared to the baseline.
- **GeoOFF** and **GeoPLY** are for example smaller compared to the input OBJ file's, because of the missing line prefix. While vertices and faces are marked with `v` and `f` in OBJ, this prefix is implicitly given by the ordering and the number of elements in the two mentioned file formats (and their base formats `OFF` and `PLY`). The line prefix results in a comparable high overhead, when it comes to files with thousands of lines.
- In some examples (e.g. horse.obj) the size difference can be lead back to the number of digits. While the input file uses 17 digits for local files, our framework uses a maximum of 13 digits for geo-referenced coordinates. This is also the reason why for example CityJSON or GeoOBJ is below the baseline.

@pointan We definitely should rework the comparison to clarify this, or at least also normalize the number of digits in the input files like we do for the features.
